services:
  # Layanan Frontend (Nginx)
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  # Layanan Backend (PHP dengan Apache)
  backend:
    build:
      context: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  # Layanan Database (MySQL)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: rakyat_melapor_db # Nama database baru
    volumes:
      - db_data:/var/lib/mysql
      - ./backend:/docker-entrypoint-initdb.d # init.sql akan dibaca dari sini

  # Layanan phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:5.2.2-apache # Versi spesifik
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: # Definisi volume untuk data database
