name: Deploy Frontend to Azure Container Apps

on:
  push:
    branches:
      - master # Ganti dengan branch utama Anda
    paths:
      - 'frontend/**' # Trigger jika ada perubahan di folder frontend

env:
  AZURE_RESOURCE_GROUP: RakyatMelaporGroup
  AZURE_CONTAINER_APPS_ENVIRONMENT: rakyatmelapor-env
  AZURE_LOCATION: southeastasia # Lokasi Azure Anda
  CONTAINER_APP_NAME: rakyat-melapor-frontend-app # Nama Container App frontend
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
  IMAGE_NAME: rakyat-melapor-frontend
  NGINX_DOCKERFILE_PATH: ./frontend/Dockerfile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image for frontend
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend # Konteks build adalah folder frontend
          file: ${{ env.NGINX_DOCKERFILE_PATH }}
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/frontend
          containerAppEnvironment: ${{ env.AZURE_CONTAINER_APPS_ENVIRONMENT }}
          resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          targetPort: 80 # Port yang diekspos oleh Nginx di container
          ingress: external # Akses dari luar (ini adalah aplikasi web)
          # minReplicas: 1
          # maxReplicas: 1

